services:
  - type: web
    name: rabbitmq
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: RENDER_EXTERNAL_HOSTNAME
        value: YOUR_SERVICE_URL
    port: 15672
